### ISSUE TITLE
store is not resolve

### ISSUE THREAD

**Issue by ZhaoTim** [CareyToboo/rt-admin#1]
util文件里的storage.js里面引入store，我没找到在哪里导出的store啊，麻烦了

**Comment by CareyToboo** [comment]
https://github.com/CareyToboo/rt-admin/blob/e818fb9428a9fa855f452d6ae88eb4c4985cfdbd/package.json#L51

非常感谢你提的issue。确实是一个严重BUG，已经修复。
> 如果有遇到任何问题，欢迎提issue。项目功能和优化还在迭代中.
