### ISSUE TITLE
考虑出个 js sdk 版本吗？

### ISSUE THREAD

**Issue by faceair** [CareyToboo/rt-admin#6]
类似于 amis 的 js sdk 用法

**Comment by CareyToboo** [comment]
正在做 NPM 包的 cli 版本，简化了很多强react依赖，可完全不关心react运行。只有高级自定义功能，需要用到react自定义组件。即使用到也是最基本的react jsx写法，和html tag 一样。但是这是一个完整的框架，只能在在系统中使用，不能类似amis, 在已存在的系统中使用。

**Comment by faceair** [comment]
cli 或者各种 boilerplate 都可以降低使用成本，这个是肯定的。
但我更喜欢 js sdk 的一点在于，我可以把 admin 后台的 html 文件直接放在后端项目里维护，不需要单独配置一堆目录和走一遍构建流程，简单编辑 html 里嵌入的 json 就可以了。
我尝试通过这个方式维护过一个 1k 多行 amis json 配置的完整后台，需要复用的模块都定义在 definition 里了，用起来感觉比较方便。
如果能 rt-admin 考虑也增加这种使用方式就更好了~

**Comment by CareyToboo** [comment]
那目前没有暂时没有考虑单独出JSSDK，JSSDK 局限性太大了。因为RT的目标是做，完整统一的 ` 可视化编辑 Admin ` 系统。  第一步使用 `CLI版本` 作为过渡，可实现很多JSSDK不能实现的功能，代码打包优化、主题扩展、开发体验、项目架构基础功能。第二步就再做可视化编辑器。个人觉得 `JSSDK` 在维护已存在的项目中有一定价值。开发新系统，或者重构老系统，都没有特别的价值。

你说的需求，在 `RT-CLI` 更容易实现，公用逻辑更容复用，而且还可以随意自定义组件。（前提是必须是新建项目）

**Comment by faceair** [comment]
好的，明白了 👍
